---
title: "Reference"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

/* latin-ext */
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHjxAwXiWtFCfQ7A.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHjx4wXiWtFCc.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

p {
  font-family: 'Lato', sans-serif;
}

h1 {
  font-family: 'Lato', sans-serif;
}

h2 {
  font-family: 'Lato', sans-serif;
}

h3 {
  font-family: 'Lato', sans-serif;
}

h4 {
  font-family: 'Lato', sans-serif;
}

.list {
  font-family: 'Lato', sans-serif;
}

</style>
</head>
<body>
<br>
<div class="list">
### Coding Guides
- <a href="https://www.rstudio.com/resources/cheatsheets/ " target="_blank">RStudio Website Cheat Sheet</a>
- <a href = "(https://dss.princeton.edu/training/RStudio101.pdf" target="_blank"> Princeton presentation</a>
- <a href="http://www.r-tutor.com/" target="_blank">R-Tutor</a>
- <a href = "https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf" target="_blank">R for Beginnners</a>
- <a href="https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf" target="_blank">Torfs Guidebook</a>
- <a href = "http://whitlockschluter.zoology.ubc.ca/r-code" target="_blank">WS2e Webpage</a>


<br>

### Stylistic Guides
- <a href ="http://www.endmemo.com/program/R/pchsymbols.php" target="_blank">Symbol types for pch</a>
- <a href ="http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf" target="_blank">Accepted colors</a>
- <a href ="https://www.w3schools.com/colors/colors_picker.asp" target="_blank">HTML color code values</a>

</div>
</body>
</html>